#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

mouse="Kensington      Kensington Expert Mouse"

# Set correct buttons
xinput set-button-map "$mouse" 1 8 3 4 5 6 7 9 2

[ -r ~/.fehbg ] && sh ~/.fehbg

/usr/bin/xset r rate 200 30
/usr/bin/setxkbmap -layout us -option 'compose:ralt'
