alias llusb="system_profiler SPUSBDataType"
alias lstty="ls -la /dev/cu.*"
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport'
alias lswifi='/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -s | sed 1d | sort -rnk 3'
alias psy="sudo port sync"
alias p='port'
alias sp='sudo port'
alias pi='portindex'
#alias p='noglob port-wrapper'
