#!/usr/bin/env zsh
function pcc() {
    if [[ -z $1 && ! -e $PWD/Portfile ]]; then
        echo "Usage: pcc portname"
        return -1
    fi
    sudo port -v checksum $1 2>/dev/null | grep -E '^checksums| {20}'
}
