#!/usr/bin/env zsh
function acronym() {
    echo "Acronyms for $1:"
    elinks --dump http://www.acronymfinder.com/$1.html | sed -e '/*/!d' -e 's/*/✪ /g' -e 's/ *\[.*\]/|/' -e 's/^ *//' | column -s '|' -t;
}
