#!/usr/bin/env zsh -f
function checksum(){
    if [ -f "$1" ]; then
	basename $1 | sed -e "s/\(.*\)/\1 \\\/"
	md5 $1 | sed -e "s/^MD5.*=/md5/" | sed -e "s/\(.*\)/\1 \\\/"
	openssl sha256 $1 | sed -e "s/^SHA256.*=/sha256/" | sed -e "s/\(.*\)/\1 \\\/"
	openssl rmd160 $1 | sed -e "s/^R.*=/rmd160/"
    else
	echo "Usage: $0 filename"
    fi
}
